# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' grow_acd() : grow tree list with Acadian Variant of FVS optionally using metric or imperial units.
#'
#' @param periods    : Integer | Number of periods to project the tree list
#' @param Region     : String  | Region code: 'ME' (Maine), 'NB' (New Brunswick)
#' @param year       : Integer | Current year or age of stand
#' @param units      : Integer | 0 = metric, 1 = imperial
#' @param csi        : Numeric | Site Index (meters or feet)
#' @param elev       : Numeric | Elevation (meters or feet)
#' @param cdef       : Numeric | Cumulative Defoliation Percentage (between 0 and 1)
#' @param use_sbw    : Integer | Use Spruce Budworm Modifiers (0 = No, 1 = Yes)
#' @param use_hw     : Integer | Use Hardwood Risk and Form Modifiers (0 = No, 1 = Yes)
#' @param use_thin   : Integer | Use Thinning Modifiers (0 = No, 1 = Yes)
#' @param use_ingrowth : Integer | Use ingrowth functionality
#' @param cut_point  : Numeric | ingrowth probability threshold
#' @param MinDBH     : Numeric | Minimum DBH for ingrowth trees (cm or inches)
#' @param plot_id    : vector  | Plot ID
#' @param tree_id    : vector  | Tree ID
#' @param spp        : vector  | FIA Numeric Species Code
#' @param dbh        : vector  | diameter at breast height (cm or inches)
#' @param ht         : vector  | total height (meters or feet)
#' @param expf       : vector  | expansion factor, trees per hectare or per acre
#' @param cr         : vector  | crown ratio (between 0 and 1)
#' @param form       : vector  | Form Code (Castle et al. 2017) 1 through 8
#' @param risk       : vector  | Risk Code (Castle et al. 2017) 1 through 4
#' @md
#'
#' @description
#' Projects the tree list using the Acadian Variant of FVS with Metric Units.
#'
#' FIA species codes are defined here: https://www.fia.fs.usda.gov/program-features/urban/docs/Appendix%203a%20CORE%20Species%20List.pdf.
#'
#' @return
#' Returns a data.frame with the grown tree list in following variables:
#' \itemize{
#'     \item plot.id
#'     \item tree.id
#'     \item species
#'     \item dbh
#'     \item ht
#'     \item expf
#'     \item cr
#' }
#'
#' @export
grow_acd <- function(periods, Region, year, units, csi, elev, cdef, use_sbw, use_hw, use_thin, use_ingrowth, cut_point, MinDBH, plot_id, tree_id, spp, dbh, ht, expf, cr, form, risk) {
    .Call('_acdR_grow_acd', PACKAGE = 'acdR', periods, Region, year, units, csi, elev, cdef, use_sbw, use_hw, use_thin, use_ingrowth, cut_point, MinDBH, plot_id, tree_id, spp, dbh, ht, expf, cr, form, risk)
}

