// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grow_acd
Rcpp::DataFrame grow_acd(Rcpp::IntegerVector periods, Rcpp::StringVector Region, Rcpp::IntegerVector year, Rcpp::IntegerVector units, Rcpp::NumericVector csi, Rcpp::NumericVector elev, Rcpp::NumericVector cdef, Rcpp::IntegerVector use_sbw, Rcpp::IntegerVector use_hw, Rcpp::IntegerVector use_thin, Rcpp::IntegerVector use_ingrowth, Rcpp::NumericVector cut_point, Rcpp::NumericVector MinDBH, Rcpp::IntegerVector plot_id, Rcpp::IntegerVector tree_id, Rcpp::IntegerVector spp, Rcpp::NumericVector dbh, Rcpp::NumericVector ht, Rcpp::NumericVector expf, Rcpp::NumericVector cr, Rcpp::IntegerVector form, Rcpp::IntegerVector risk);
RcppExport SEXP _acdR_grow_acd(SEXP periodsSEXP, SEXP RegionSEXP, SEXP yearSEXP, SEXP unitsSEXP, SEXP csiSEXP, SEXP elevSEXP, SEXP cdefSEXP, SEXP use_sbwSEXP, SEXP use_hwSEXP, SEXP use_thinSEXP, SEXP use_ingrowthSEXP, SEXP cut_pointSEXP, SEXP MinDBHSEXP, SEXP plot_idSEXP, SEXP tree_idSEXP, SEXP sppSEXP, SEXP dbhSEXP, SEXP htSEXP, SEXP expfSEXP, SEXP crSEXP, SEXP formSEXP, SEXP riskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type periods(periodsSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type Region(RegionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type units(unitsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type csi(csiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type elev(elevSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cdef(cdefSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type use_sbw(use_sbwSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type use_hw(use_hwSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type use_thin(use_thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type use_ingrowth(use_ingrowthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cut_point(cut_pointSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type MinDBH(MinDBHSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type plot_id(plot_idSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tree_id(tree_idSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type spp(sppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ht(htSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type expf(expfSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cr(crSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type form(formSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type risk(riskSEXP);
    rcpp_result_gen = Rcpp::wrap(grow_acd(periods, Region, year, units, csi, elev, cdef, use_sbw, use_hw, use_thin, use_ingrowth, cut_point, MinDBH, plot_id, tree_id, spp, dbh, ht, expf, cr, form, risk));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_acdR_grow_acd", (DL_FUNC) &_acdR_grow_acd, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_acdR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
